version: "3"
services:
  agents-postgres:
    image: pgvector/pgvector:pg17
    networks:
      - agents-network
    environment:
      POSTGRES_DB: postgres
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - agents-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 1s

  agents-python-server:
    environment:
      - SALT=${SALT:-default_salt}
      - DBHOST=${DEFOG_DBHOST:-agents-postgres}
      - DBPORT=${DEFOG_DBPORT:-5432}
      - DATABASE=${DEFOG_DATABASE:-postgres}
      - DBUSER=${DEFOG_DBUSER:-postgres}
      - DBPASSWORD=${DEFOG_DBPASSWORD:-postgres}
      - REDIS_INTERNAL_HOST=${REDIS_INTERNAL_HOST:-agents-redis}
      - REDIS_INTERNAL_PORT=${REDIS_INTERNAL_PORT:-6379}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-true}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPATH=/backend
      - INTERNAL_DB=${INTERNAL_DB:-postgres}
      - ANALYZE_DATA=${ANALYZE_DATA:-yes}
      - ANALYZE_DATA_MODEL=${ANALYZE_DATA_MODEL:-openai}
      - PROD=${PROD:-yes}
      
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    build:
      context: .
      dockerfile: dockerfile.agents-python-server
    restart: always
    ports:
      - "1235:1235"
    volumes:
      - ./backend:/backend
    depends_on:
      agents-postgres:
        condition: service_healthy
      agents-redis:
        condition: service_healthy
    networks:
      - agents-network

  agents-nginx:
    build:
      context: .
      dockerfile: dockerfile.agents-nginx
    ports:
      - "${PORT:-80}:80"
      - "443:443"
    depends_on:
      - agents-python-server
    networks:
      - agents-network

  agents-redis:
    image: redis:7-alpine
    networks:
      - agents-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 128M
    command: >
      redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    environment:
      - REDIS_MAXMEMORY=128mb
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 1s

volumes:
  agents-postgres:
  redis-data:

networks:
  agents-network:
